from typing import TypedDict
from .enums import *


Entry = TypedDict(
    "Entry",
    {
        "timestamp": str,
        "type": UpdateType,
        "to": int,
        "from": int,
        "from_bot": bool,
        "from_firstname": str,
        "from_lastname": str,
        "from_username": str,
        "from_languagecode": str,
        "from_premium": bool,
        "from_type": ChatType,
        "from_title": str,
        "from_businessconnection": str,
        "from_boostcount": int,
        "from_signature": str,
        "to_bot": bool,
        "to_firstname": str,
        "to_lastname": str,
        "to_username": str,
        "chat_id": int,
        "chat_username": str,
        "chat_title": str,
        "chat_firstname": str,
        "chat_lastname": str,
        "chat_type": ChatType,
        "message_type": MessageType,
        "message_id": int,
        "message_threadid": int,
        "message_date": str,
        "message_topic": bool,
        "message_automaticforward": bool,
        "message_effectid": str,
        "message_replytomessageid": int,
        "message_quotetext": str,
        "forward_date": str,
        "forward_from": int,
        "forward_messageid": int,
        "forward_signature": str,
        "forward_bot": bool,
        "forward_name": str,
        "message_text": str,
        "message_url": str,
        "dice_emoji": str,
        "dice_value": int,
        "callbackquery_id": str,
        "callbackquery_inlinemessageid": str,
        "callbackquery_data": str,
        "inlinequery_id": str,
        "inlinequery_text": str,
        "inlinequery_offset": str,
        "inlineresultchosen_id": str,
        "inlineresultchosen_query": str,
        "inlineresultchosen_inlinemessageid": str,
        "chatmember_id": int,
        "chatmember_bot": bool,
        "chatmember_firstname": str,
        "chatmember_lastname": str,
        "chatmember_username": str,
        "chatmember_premium": bool,
        "chatmember_oldstatus": ChatMemberStatus,
        "chatmember_newstatus": ChatMemberStatus,
        "payload": str,
    },
)
