from enum import IntEnum

MessageType = IntEnum(
    "MessageType",
    [
        "Unsupported",
        "Text",
        "Link",
        "Photo",
        "Document",
        "Video",
        "Sticker",
        "Animation",
        "Voice",
        "Audio",
        "Dice",
        "VideoNote",
        "Contact",
        "Game",
        "Poll",
        "Invoice",
        "Venue",
        "Location",
        "NewChatMembers",
        "LeftChatMember",
        "NewChatTitle",
        "NewChatPhoto",
        "DeletedChatPhoto",
        "GroupCreated",
        "SupergroupCreated",
        "ChannelCreated",
        "AutoDeleteTimerChanged",
        "ChatMigratedTo",
        "ChatMigratedFrom",
        "PinnedMessage",
        "UserShared",
        "WriteAccessAllowed",
        "ForumTopicCreated",
        "ForumTopicEdited",
        "ForumTopicClosed",
        "ForumTopicReopened",
        "VideoChatScheduled",
        "VideoChatStarted",
        "VideoChatEnded",
        "Giveaway",
        "SuccessfulPayment",
        "RefundedPayment",
    ],
    start=0,
)

__all__ = ["MessageType"]
